### ISSUE TITLE
unityInstance is not defined

### ISSUE THREAD

**Issue by johnedvard** [TheRoccoB/web-monetization-unity-webgl#1]
Hello, and thank you for the asset.
I am having some issues trying to use it in Unity `2020.1.11f1`
After exporting to WebGL, I get the following error when Monetization start. I am not sure what causes this, and was hoping for some help on the matter.

```
Invoking error handler due to
ReferenceError: unityInstance is not defined
    at sendMessageToWebMonetizationBroadcaster (http://localhost:60126/Build/DemoWebMonetization4.framework.js:2:42955)
    at HTMLDivElement.<anonymous> (http://localhost:60126/Build/DemoWebMonetization4.framework.js:2:43117)
    at <anonymous>:6:33
DemoWebMonetization4.framework.js:2 Uncaught ReferenceError: unityInstance is not defined
    at sendMessageToWebMonetizationBroadcaster (DemoWebMonetization4.framework.js:2)
    at HTMLDivElement.<anonymous> (DemoWebMonetization4.framework.js:2)
    at <anonymous>:6:33
```

![Screenshot 2020-11-01 at 22 18 01](https://user-images.githubusercontent.com/656024/97804036-9411e080-1c90-11eb-8553-4a09792b9145.png)

**Comment by johnedvard** [comment]
I noticed that there have been some changes in 2020.1 https://forum.unity.com/threads/changes-to-the-webgl-loader-and-templates-introduced-in-unity-2020-1.817698/ I will either make some adjustments myself, or use an older version of Unity

I tried Unity 2019.4.13f1, and now it works.
